package responses

type Confirmation struct {
	D struct {
		Results []struct {
			Metadata struct {
				ID   string `json:"id"`
				URI  string `json:"uri"`
				Type string `json:"type"`
			} `json:"__metadata"`
			ConfirmationGroup              string      `json:"ConfirmationGroup"`
			ConfirmationCount              string      `json:"ConfirmationCount"`
			OrderID                        string      `json:"OrderID"`
			OrderOperation                 string      `json:"OrderOperation"`
			OrderSuboperation              string      `json:"OrderSuboperation"`
			OrderType                      string      `json:"OrderType"`
			OrderOperationInternalID       string      `json:"OrderOperationInternalID"`
			ConfirmationText               string      `json:"ConfirmationText"`
			Language                       string      `json:"Language"`
			Material                       string      `json:"Material"`
			OrderPlannedTotalQty           string      `json:"OrderPlannedTotalQty"`
			ProductionUnit                 string      `json:"ProductionUnit"`
			FinalConfirmationType          string      `json:"FinalConfirmationType"`
			IsFinalConfirmation            bool        `json:"IsFinalConfirmation"`
			OpenReservationsIsCleared      bool        `json:"OpenReservationsIsCleared"`
			IsReversed                     bool        `json:"IsReversed"`
			IsReversal                     bool        `json:"IsReversal"`
			APIConfHasNoGoodsMovements     bool        `json:"APIConfHasNoGoodsMovements"`
			OrderConfirmationRecordType    string      `json:"OrderConfirmationRecordType"`
			ConfirmationEntryDate          string      `json:"ConfirmationEntryDate"`
			ConfirmationEntryTime          string      `json:"ConfirmationEntryTime"`
			EnteredByUser                  string      `json:"EnteredByUser"`
			LastChangeDate                 string      `json:"LastChangeDate"`
			LastChangedByUser              string      `json:"LastChangedByUser"`
			ConfirmationExternalEntryDate  string      `json:"ConfirmationExternalEntryDate"`
			ConfirmationExternalEntryTime  string      `json:"ConfirmationExternalEntryTime"`
			EnteredByExternalUser          string      `json:"EnteredByExternalUser"`
			ExternalSystemConfirmation     string      `json:"ExternalSystemConfirmation"`
			Plant                          string      `json:"Plant"`
			WorkCenterTypeCode             string      `json:"WorkCenterTypeCode"`
			WorkCenter                     string      `json:"WorkCenter"`
			Personnel                      string      `json:"Personnel"`
			TimeRecording                  string      `json:"TimeRecording"`
			EmployeeWageType               string      `json:"EmployeeWageType"`
			EmployeeWageGroup              string      `json:"EmployeeWageGroup"`
			BreakDurationUnit              string      `json:"BreakDurationUnit"`
			ConfirmedBreakDuration         string      `json:"ConfirmedBreakDuration"`
			EmployeeSuitability            string      `json:"EmployeeSuitability"`
			NumberOfEmployees              string      `json:"NumberOfEmployees"`
			PostingDate                    string      `json:"PostingDate"`
			ConfirmedExecutionStartDate    string      `json:"ConfirmedExecutionStartDate"`
			ConfirmedExecutionStartTime    string      `json:"ConfirmedExecutionStartTime"`
			ConfirmedSetupEndDate          string      `json:"ConfirmedSetupEndDate"`
			ConfirmedSetupEndTime          string      `json:"ConfirmedSetupEndTime"`
			ConfirmedProcessingStartDate   string      `json:"ConfirmedProcessingStartDate"`
			ConfirmedProcessingStartTime   string      `json:"ConfirmedProcessingStartTime"`
			ConfirmedProcessingEndDate     string      `json:"ConfirmedProcessingEndDate"`
			ConfirmedProcessingEndTime     string      `json:"ConfirmedProcessingEndTime"`
			ConfirmedTeardownStartDate     string      `json:"ConfirmedTeardownStartDate"`
			ConfirmedTeardownStartTime     string      `json:"ConfirmedTeardownStartTime"`
			ConfirmedExecutionEndDate      string      `json:"ConfirmedExecutionEndDate"`
			ConfirmedExecutionEndTime      string      `json:"ConfirmedExecutionEndTime"`
			ConfirmationUnit               string      `json:"ConfirmationUnit"`
			ConfirmationYieldQuantity      string      `json:"ConfirmationYieldQuantity"`
			ConfirmationScrapQuantity      string      `json:"ConfirmationScrapQuantity"`
			VarianceReasonCode             string      `json:"VarianceReasonCode"`
			OpWorkQuantityUnit1            string      `json:"OpWorkQuantityUnit1"`
			OpConfirmedWorkQuantity1       string      `json:"OpConfirmedWorkQuantity1"`
			NoFurtherOpWorkQuantity1IsExpd bool        `json:"NoFurtherOpWorkQuantity1IsExpd"`
			OpWorkQuantityUnit2            string      `json:"OpWorkQuantityUnit2"`
			OpConfirmedWorkQuantity2       string      `json:"OpConfirmedWorkQuantity2"`
			NoFurtherOpWorkQuantity2IsExpd bool        `json:"NoFurtherOpWorkQuantity2IsExpd"`
			OpWorkQuantityUnit3            string      `json:"OpWorkQuantityUnit3"`
			OpConfirmedWorkQuantity3       string      `json:"OpConfirmedWorkQuantity3"`
			NoFurtherOpWorkQuantity3IsExpd bool        `json:"NoFurtherOpWorkQuantity3IsExpd"`
			OpWorkQuantityUnit4            string      `json:"OpWorkQuantityUnit4"`
			OpConfirmedWorkQuantity4       string      `json:"OpConfirmedWorkQuantity4"`
			NoFurtherOpWorkQuantity4IsExpd bool        `json:"NoFurtherOpWorkQuantity4IsExpd"`
			OpWorkQuantityUnit5            string      `json:"OpWorkQuantityUnit5"`
			OpConfirmedWorkQuantity5       string      `json:"OpConfirmedWorkQuantity5"`
			NoFurtherOpWorkQuantity5IsExpd bool        `json:"NoFurtherOpWorkQuantity5IsExpd"`
			OpWorkQuantityUnit6            string      `json:"OpWorkQuantityUnit6"`
			OpConfirmedWorkQuantity6       string      `json:"OpConfirmedWorkQuantity6"`
			NoFurtherOpWorkQuantity6IsExpd bool        `json:"NoFurtherOpWorkQuantity6IsExpd"`
			BusinessProcessEntryUnit       string      `json:"BusinessProcessEntryUnit"`
			BusinessProcessConfirmedQty    string      `json:"BusinessProcessConfirmedQty"`
			NoFurtherBusinessProcQtyIsExpd bool        `json:"NoFurtherBusinessProcQtyIsExpd"`
		} `json:"results"`
	} `json:"d"`
}