package sap_api_input_reader

type EC_MC struct {
	ConnectionKey string      `json:"connection_key"`
	Result        bool        `json:"result"`
	RedisKey      string      `json:"redis_key"`
	Filepath      string      `json:"filepath"`
	ProductionOrder struct {
		ManufacturingOrder             string      `json:"document_no"`
		DeliverTo                      string      `json:"deliver_to"`
		MfgOrderItemPlannedTotalQty    string      `json:"quantity"`
		MfgOrderItemActualDeviationQty string      `json:"picked_quantity"`
		Price                          string      `json:"price"`
	  Batch                          string      `json:"batch"`
	} `json:"document"`
	ManufacturingOrder struct {
		ManufacturingOrder             string      `json:"document_no"`
		StatusCode                     string      `json:"status"`
		DeliverTo                      string      `json:"deliver_to"`
		MfgOrderItemPlannedTotalQty    string      `json:"quantity"`
		MfgOrderItemActualDeviationQty string      `json:"completed_quantity"`
	    PlannedStartDate               string      `json:"planned_start_date"`
	    MfgOrderItemPlndDeliveryDate   string      `json:"planned_validated_date"`
	    ActualStartDate                string      `json:"actual_start_date"`
	    MfgOrderItemActualDeliveryDate string      `json:"actual_validated_date"`
	    Batch                          string      `json:"batch"`
		BillOfOperations struct {
			OrderIntBillOfOperationsItem string      `json:"work_no"`
			OpPlannedTotalQuantity       string      `json:"quantity"`
			OpTotalConfirmedYieldQty     string      `json:"completed_quantity"`
			ErroredQuantity              string      `json:"errored_quantity"`
			Component                    string      `json:"component"`
			MaterialCompOriginalQuantity string      `json:"planned_component_quantity"`
			OpErlstSchedldExecStrtDte    string      `json:"planned_start_date"`
			OpErlstSchedldExecStrtTme    string      `json:"planned_start_time"`
			OpErlstSchedldExecEndDte     string      `json:"planned_validated_date"`
			OpErlstSchedldExecEndTme     string      `json:"planned_validated_time"`
			OpActualExecutionStartDate   string      `json:"actual_start_date"`
			OpActualExecutionStartTime   string      `json:"actual_start_time"`
			OpActualExecutionEndDate     string      `json:"actual_validated_date"`
			OpActualExecutionEndTime     string      `json:"actual_validated_time"`
		} `json:"work"`
	} `json:"production_order"`
	APISchema                      string      `json:"api_schema"`
	MaterialCode                   string      `json:"material_code"`
	ProductionPlant                string      `json:"plant/supplier"`
	Stock                          string      `json:"stock"`
	ManufacturingOrderType         string      `json:"document_type"`
	ManufacturingOrderNo           string      `json:"document_no"`
	MfgOrderItemPlndDeliveryDate   string      `json:"planned_date"`
	MfgOrderItemActualDeliveryDate string      `json:"validated_date"`
	Deleted                        bool        `json:"deleted"`
}

type SDC struct {
	ConnectionKey            string `json:"connection_key"`
	Result                   bool   `json:"result"`
	RedisKey                 string `json:"redis_key"`
	Filepath                 string `json:"filepath"`
	ProcessOrderConfirmation struct {
		ConfirmationGroup              string      `json:"ConfirmationGroup"`
		ConfirmationCount              string      `json:"ConfirmationCount"`
		OrderID                        string      `json:"OrderID"`
		OrderOperation                 string      `json:"OrderOperation"`
		OrderSuboperation              string      `json:"OrderSuboperation"`
		OrderType                      string      `json:"OrderType"`
		OrderOperationInternalID       string      `json:"OrderOperationInternalID"`
		ConfirmationText               string      `json:"ConfirmationText"`
		Language                       string      `json:"Language"`
		Material                       string      `json:"Material"`
		OrderPlannedTotalQty           string      `json:"OrderPlannedTotalQty"`
		ProductionUnit                 string      `json:"ProductionUnit"`
		FinalConfirmationType          string      `json:"FinalConfirmationType"`
		IsFinalConfirmation            bool        `json:"IsFinalConfirmation"`
		OpenReservationsIsCleared      bool        `json:"OpenReservationsIsCleared"`
		IsReversed                     bool        `json:"IsReversed"`
		IsReversal                     bool        `json:"IsReversal"`
		APIConfHasNoGoodsMovements     bool        `json:"APIConfHasNoGoodsMovements"`
		OrderConfirmationRecordType    string      `json:"OrderConfirmationRecordType"`
		ConfirmationEntryDate          string      `json:"ConfirmationEntryDate"`
		ConfirmationEntryTime          string      `json:"ConfirmationEntryTime"`
		EnteredByUser                  string      `json:"EnteredByUser"`
		LastChangeDate                 string      `json:"LastChangeDate"`
		LastChangedByUser              string      `json:"LastChangedByUser"`
		ConfirmationExternalEntryDate  string      `json:"ConfirmationExternalEntryDate"`
		ConfirmationExternalEntryTime  string      `json:"ConfirmationExternalEntryTime"`
		EnteredByExternalUser          string      `json:"EnteredByExternalUser"`
		ExternalSystemConfirmation     string      `json:"ExternalSystemConfirmation"`
		Plant                          string      `json:"Plant"`
		WorkCenterTypeCode             string      `json:"WorkCenterTypeCode"`
		WorkCenter                     string      `json:"WorkCenter"`
		Personnel                      string      `json:"Personnel"`
		TimeRecording                  string      `json:"TimeRecording"`
		EmployeeWageType               string      `json:"EmployeeWageType"`
		EmployeeWageGroup              string      `json:"EmployeeWageGroup"`
		BreakDurationUnit              string      `json:"BreakDurationUnit"`
		ConfirmedBreakDuration         string      `json:"ConfirmedBreakDuration"`
		EmployeeSuitability            string      `json:"EmployeeSuitability"`
		NumberOfEmployees              string      `json:"NumberOfEmployees"`
		PostingDate                    string      `json:"PostingDate"`
		ConfirmedExecutionStartDate    string      `json:"ConfirmedExecutionStartDate"`
		ConfirmedExecutionStartTime    string      `json:"ConfirmedExecutionStartTime"`
		ConfirmedSetupEndDate          string      `json:"ConfirmedSetupEndDate"`
		ConfirmedSetupEndTime          string      `json:"ConfirmedSetupEndTime"`
		ConfirmedProcessingStartDate   string      `json:"ConfirmedProcessingStartDate"`
		ConfirmedProcessingStartTime   string      `json:"ConfirmedProcessingStartTime"`
		ConfirmedProcessingEndDate     string      `json:"ConfirmedProcessingEndDate"`
		ConfirmedProcessingEndTime     string      `json:"ConfirmedProcessingEndTime"`
		ConfirmedTeardownStartDate     string      `json:"ConfirmedTeardownStartDate"`
		ConfirmedTeardownStartTime     string      `json:"ConfirmedTeardownStartTime"`
		ConfirmedExecutionEndDate      string      `json:"ConfirmedExecutionEndDate"`
		ConfirmedExecutionEndTime      string      `json:"ConfirmedExecutionEndTime"`
		ConfirmationUnit               string      `json:"ConfirmationUnit"`
		ConfirmationYieldQuantity      string      `json:"ConfirmationYieldQuantity"`
		ConfirmationScrapQuantity      string      `json:"ConfirmationScrapQuantity"`
		VarianceReasonCode             string      `json:"VarianceReasonCode"`
		OpWorkQuantityUnit1            string      `json:"OpWorkQuantityUnit1"`
		WorkQuantityUnit1ISOCode       string      `json:"WorkQuantityUnit1ISOCode"`
		WorkQuantityUnit1SAPCode       string      `json:"WorkQuantityUnit1SAPCode"`
		OpConfirmedWorkQuantity1       string      `json:"OpConfirmedWorkQuantity1"`
		NoFurtherOpWorkQuantity1IsExpd bool        `json:"NoFurtherOpWorkQuantity1IsExpd"`
		OpWorkQuantityUnit2            string      `json:"OpWorkQuantityUnit2"`
		OpConfirmedWorkQuantity2       string      `json:"OpConfirmedWorkQuantity2"`
		NoFurtherOpWorkQuantity2IsExpd bool        `json:"NoFurtherOpWorkQuantity2IsExpd"`
		OpWorkQuantityUnit3            string      `json:"OpWorkQuantityUnit3"`
		OpConfirmedWorkQuantity3       string      `json:"OpConfirmedWorkQuantity3"`
		NoFurtherOpWorkQuantity3IsExpd bool        `json:"NoFurtherOpWorkQuantity3IsExpd"`
		OpWorkQuantityUnit4            string      `json:"OpWorkQuantityUnit4"`
		OpConfirmedWorkQuantity4       string      `json:"OpConfirmedWorkQuantity4"`
		NoFurtherOpWorkQuantity4IsExpd bool        `json:"NoFurtherOpWorkQuantity4IsExpd"`
		OpWorkQuantityUnit5            string      `json:"OpWorkQuantityUnit5"`
		OpConfirmedWorkQuantity5       string      `json:"OpConfirmedWorkQuantity5"`
		NoFurtherOpWorkQuantity5IsExpd bool        `json:"NoFurtherOpWorkQuantity5IsExpd"`
		OpWorkQuantityUnit6            string      `json:"OpWorkQuantityUnit6"`
		OpConfirmedWorkQuantity6       string      `json:"OpConfirmedWorkQuantity6"`
		NoFurtherOpWorkQuantity6IsExpd bool        `json:"NoFurtherOpWorkQuantity6IsExpd"`
		BusinessProcessEntryUnit       string      `json:"BusinessProcessEntryUnit"`
		BusinessProcessConfirmedQty    string      `json:"BusinessProcessConfirmedQty"`
		NoFurtherBusinessProcQtyIsExpd bool        `json:"NoFurtherBusinessProcQtyIsExpd"`
		MaterialMovements              struct {
			MaterialDocument           string      `json:"MaterialDocument"`
			MaterialDocumentItem       string      `json:"MaterialDocumentItem"`
			MaterialDocumentYear       string      `json:"MaterialDocumentYear"`
			OrderType                  string      `json:"OrderType"`
			OrderID                    string      `json:"OrderID"`
			OrderItem                  string      `json:"OrderItem"`
			ManufacturingOrderCategory string      `json:"ManufacturingOrderCategory"`
			Material                   string      `json:"Material"`
			Plant                      string      `json:"Plant"`
			Reservation                string      `json:"Reservation"`
			ReservationItem            string      `json:"ReservationItem"`
			StorageLocation            string      `json:"StorageLocation"`
			ProductionSupplyArea       string      `json:"ProductionSupplyArea"`
			Batch                      string      `json:"Batch"`
			InventoryValuationType     string      `json:"InventoryValuationType"`
			GoodsMovementType          string      `json:"GoodsMovementType"`
			GoodsMovementRefDocType    string      `json:"GoodsMovementRefDocType"`
			InventoryUsabilityCode     string      `json:"InventoryUsabilityCode"`
			InventorySpecialStockType  string      `json:"InventorySpecialStockType"`
			SalesOrder                 string      `json:"SalesOrder"`
			SalesOrderItem             string      `json:"SalesOrderItem"`
			WBSElementExternalID       string      `json:"WBSElementExternalID"`
			Supplier                   string      `json:"Supplier"`
			Customer                   string      `json:"Customer"`
			ReservationIsFinallyIssued bool        `json:"ReservationIsFinallyIssued"`
			IsCompletelyDelivered      bool        `json:"IsCompletelyDelivered"`
			ShelfLifeExpirationDate    string      `json:"ShelfLifeExpirationDate"`
			ManufactureDate            string      `json:"ManufactureDate"`
			StorageType                string      `json:"StorageType"`
			StorageBin                 string      `json:"StorageBin"`
			MaterialDocumentItemText   string      `json:"MaterialDocumentItemText"`
			EntryUnit                  string      `json:"EntryUnit"`
			QuantityInEntryUnit        string      `json:"QuantityInEntryUnit"`
			BatchCharacteristic        struct {
				Batch           string `json:"Batch"`
				CharcInternalID string `json:"CharcInternalID"`
				Characteristic  string `json:"Characteristic"`
				CharcValue      string `json:"CharcValue"`
			} `json:"BatchCharacteristic"`
		} `json:"MaterialMovements"`
	} `json:"ProcessOrderConfirmation"`
	APISchema    string   `json:"api_schema"`
	Accepter     []string `json:"accepter"`
	ProcessOrder string   `json:"process_order"`
	Deleted      bool     `json:"deleted"`
}
